name: Generate News Markdown and Sitemap

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # كل ساعة

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run main.py (إنشاء ملفات md)
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python main.py

    - name: Run feed.py (توليد feed.xml)
      run: python feed.py

    - name: Run sitemap.py (توليد sitemap.xml)
      run: python sitemap.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add news/*.md news/lastpost.txt feed.xml sitemap.xml
        git diff --cached --quiet || git commit -m "تحديث تلقائي للأخبار وخريطة الموقع"
        git push
