name: Generate sitemap.xml

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate sitemap.xml
        run: python sitemap.py

      - name: Pull latest changes
        run: git pull --rebase origin main

      - name: Commit and push sitemap.xml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap.xml" || echo "No changes to commit"
          git push origin main
